# Generated by Django 5.1 on 2024-08-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
