# Generated by Django 5.1 on 2024-08-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='status',
        ),
    ]
