# Generated by Django 5.1 on 2024-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_checkout_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='order_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
