# Generated by Django 5.1 on 2024-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_checkout_id_checkout_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
